var demoData = [
   {"release date": "Tue Jan 10 2017", "contract type": "works contracts", "contract value": "48019", "supplier size": "1228"},
   {"release date": "Tue Jan 10 2017", "contract type": "social and other specific services", "contract value": "2791", "supplier size": "147"},
   {"release date": "Wed Jan 18 2017", "contract type": "works contracts", "contract value": "2407", "supplier size": "63"},
   {"release date": "Thu Jan 26 2017", "contract type": "social and other specific services", "contract value": "1674", "supplier size": "94"},
   {"release date": "Wed Feb 01 2017", "contract type": "works contracts", "contract value": "67940", "supplier size": "650"},
   {"release date": "Fri Feb 03 2017", "contract type": "works contracts", "contract value": "73533", "supplier size": "846"},
   {"release date": "Thu Feb 09 2017", "contract type": "supplies and service contracts", "contract value": "2508", "supplier size": "64"},
   {"release date": "Mon Feb 13 2017", "contract type": "works contracts", "contract value": "12603", "supplier size": "585"},
   {"release date": "Sun Feb 19 2017", "contract type": "works contracts", "contract value": "63746", "supplier size": "815"},
   {"release date": "Wed Feb 22 2017", "contract type": "social and other specific services", "contract value": "27736", "supplier size": "869"},
   {"release date": "Sat Feb 25 2017", "contract type": "social and other specific services", "contract value": "2170", "supplier size": "123"},
   {"release date": "Mon Mar 06 2017", "contract type": "social and other specific services", "contract value": "6789", "supplier size": "366"},
   {"release date": "Fri Mar 10 2017", "contract type": "works contracts", "contract value": "2884", "supplier size": "111"},
   {"release date": "Tue Mar 14 2017", "contract type": "social and other specific services", "contract value": "5491", "supplier size": "432"},
   {"release date": "Tue Mar 21 2017", "contract type": "works contracts", "contract value": "2824", "supplier size": "111"},
   {"release date": "Wed Mar 22 2017", "contract type": "social and other specific services", "contract value": "1994", "supplier size": "53"},
   {"release date": "Fri Mar 31 2017", "contract type": "supplies and service contracts", "contract value": "1270", "supplier size": "131"},
   {"release date": "Sun Apr 02 2017", "contract type": "supplies and service contracts", "contract value": "69689", "supplier size": "1440"},
   {"release date": "Fri Apr 07 2017", "contract type": "supplies and service contracts", "contract value": "1855", "supplier size": "98"},
   {"release date": "Sat Apr 08 2017", "contract type": "works contracts", "contract value": "2097", "supplier size": "53"},
   {"release date": "Fri Apr 14 2017", "contract type": "works contracts", "contract value": "11210", "supplier size": "746"},
   {"release date": "Thu Apr 20 2017", "contract type": "supplies and service contracts", "contract value": "2954", "supplier size": "129"},
   {"release date": "Mon Apr 24 2017", "contract type": "supplies and service contracts", "contract value": "2781", "supplier size": "141"},
   {"release date": "Wed Apr 26 2017", "contract type": "works contracts", "contract value": "1056", "supplier size": "87"},
   {"release date": "Thu May 04 2017", "contract type": "social and other specific services", "contract value": "5416", "supplier size": "723"},
   {"release date": "Fri May 12 2017", "contract type": "works contracts", "contract value": "10764", "supplier size": "663"},
   {"release date": "Wed May 17 2017", "contract type": "supplies and service contracts", "contract value": "1648", "supplier size": "118"},
   {"release date": "Tue May 23 2017", "contract type": "social and other specific services", "contract value": "36996", "supplier size": "569"},
   {"release date": "Sun May 28 2017", "contract type": "supplies and service contracts", "contract value": "2148", "supplier size": "99"},
   {"release date": "Sun Jun 04 2017", "contract type": "social and other specific services", "contract value": "2699", "supplier size": "55"},
   {"release date": "Wed Jun 07 2017", "contract type": "social and other specific services", "contract value": "6978", "supplier size": "610"},
   {"release date": "Thu Jun 08 2017", "contract type": "supplies and service contracts", "contract value": "12710", "supplier size": "709"},
   {"release date": "Tue Jun 13 2017", "contract type": "works contracts", "contract value": "29813", "supplier size": "944"},
   {"release date": "Fri Jun 16 2017", "contract type": "social and other specific services", "contract value": "14152", "supplier size": "563"},
   {"release date": "Sat Jun 17 2017", "contract type": "social and other specific services", "contract value": "1426", "supplier size": "76"},
   {"release date": "Mon Jun 19 2017", "contract type": "social and other specific services", "contract value": "1842", "supplier size": "122"},
   {"release date": "Fri Jun 23 2017", "contract type": "supplies and service contracts", "contract value": "46342", "supplier size": "1050"},
   {"release date": "Sat Jun 24 2017", "contract type": "works contracts", "contract value": "25436", "supplier size": "598"},
   {"release date": "Mon Jun 26 2017", "contract type": "supplies and service contracts", "contract value": "37071", "supplier size": "930"},
   {"release date": "Tue Jun 27 2017", "contract type": "supplies and service contracts", "contract value": "2339", "supplier size": "62"},
   {"release date": "Wed Jul 05 2017", "contract type": "social and other specific services", "contract value": "1757", "supplier size": "126"},
   {"release date": "Sun Jul 09 2017", "contract type": "supplies and service contracts", "contract value": "1438", "supplier size": "54"},
   {"release date": "Sun Jul 09 2017", "contract type": "supplies and service contracts", "contract value": "1430", "supplier size": "51"},
   {"release date": "Sat Jul 15 2017", "contract type": "supplies and service contracts", "contract value": "2947", "supplier size": "81"},
   {"release date": "Sat Jul 22 2017", "contract type": "supplies and service contracts", "contract value": "6227", "supplier size": "428"},
   {"release date": "Thu Jul 27 2017", "contract type": "works contracts", "contract value": "1592", "supplier size": "105"},
   {"release date": "Fri Jul 28 2017", "contract type": "social and other specific services", "contract value": "73419", "supplier size": "1390"},
   {"release date": "Fri Jul 28 2017", "contract type": "supplies and service contracts", "contract value": "2650", "supplier size": "112"},
   {"release date": "Thu Aug 03 2017", "contract type": "works contracts", "contract value": "2692", "supplier size": "133"},
   {"release date": "Mon Aug 07 2017", "contract type": "works contracts", "contract value": "2770", "supplier size": "68"},
   {"release date": "Wed Aug 09 2017", "contract type": "works contracts", "contract value": "67851", "supplier size": "1405"},
   {"release date": "Tue Aug 15 2017", "contract type": "social and other specific services", "contract value": "9476", "supplier size": "370"},
   {"release date": "Sat Aug 19 2017", "contract type": "works contracts", "contract value": "43915", "supplier size": "785"},
   {"release date": "Sun Aug 27 2017", "contract type": "social and other specific services", "contract value": "5376", "supplier size": "580"},
   {"release date": "Thu Aug 31 2017", "contract type": "social and other specific services", "contract value": "30404", "supplier size": "867"},
   {"release date": "Fri Sep 01 2017", "contract type": "works contracts", "contract value": "2322", "supplier size": "143"},
   {"release date": "Fri Sep 01 2017", "contract type": "supplies and service contracts", "contract value": "36714", "supplier size": "699"},
   {"release date": "Fri Sep 01 2017", "contract type": "supplies and service contracts", "contract value": "6853", "supplier size": "723"},
   {"release date": "Wed Sep 06 2017", "contract type": "social and other specific services", "contract value": "1315", "supplier size": "94"},
   {"release date": "Wed Sep 13 2017", "contract type": "supplies and service contracts", "contract value": "2848", "supplier size": "128"},
   {"release date": "Wed Sep 20 2017", "contract type": "works contracts", "contract value": "1947", "supplier size": "57"},
   {"release date": "Thu Sep 21 2017", "contract type": "works contracts", "contract value": "68224", "supplier size": "750"},
   {"release date": "Mon Sep 25 2017", "contract type": "social and other specific services", "contract value": "1619", "supplier size": "63"},
   {"release date": "Fri Sep 29 2017", "contract type": "social and other specific services", "contract value": "7653", "supplier size": "645"},
   {"release date": "Sat Oct 07 2017", "contract type": "works contracts", "contract value": "65286", "supplier size": "1427"},
   {"release date": "Wed Oct 11 2017", "contract type": "works contracts", "contract value": "14133", "supplier size": "460"},
   {"release date": "Tue Oct 17 2017", "contract type": "social and other specific services", "contract value": "14132", "supplier size": "556"},
   {"release date": "Thu Oct 19 2017", "contract type": "works contracts", "contract value": "26674", "supplier size": "1409"},
   {"release date": "Mon Oct 23 2017", "contract type": "social and other specific services", "contract value": "8235", "supplier size": "540"},
   {"release date": "Wed Oct 25 2017", "contract type": "supplies and service contracts", "contract value": "48071", "supplier size": "1480"},
   {"release date": "Thu Nov 02 2017", "contract type": "social and other specific services", "contract value": "2196", "supplier size": "130"},
   {"release date": "Mon Nov 06 2017", "contract type": "supplies and service contracts", "contract value": "13713", "supplier size": "510"},
   {"release date": "Wed Nov 15 2017", "contract type": "supplies and service contracts", "contract value": "58708", "supplier size": "712"},
   {"release date": "Sun Nov 19 2017", "contract type": "supplies and service contracts", "contract value": "39045", "supplier size": "1317"},
   {"release date": "Mon Nov 27 2017", "contract type": "works contracts", "contract value": "10877", "supplier size": "638"},
   {"release date": "Wed Nov 29 2017", "contract type": "works contracts", "contract value": "32375", "supplier size": "1222"},
   {"release date": "Sun Dec 03 2017", "contract type": "supplies and service contracts", "contract value": "1869", "supplier size": "71"},
   {"release date": "Mon Dec 11 2017", "contract type": "supplies and service contracts", "contract value": "42742", "supplier size": "1494"},
   {"release date": "Mon Dec 18 2017", "contract type": "social and other specific services", "contract value": "12028", "supplier size": "690"},
   {"release date": "Tue Dec 26 2017", "contract type": "social and other specific services", "contract value": "11731", "supplier size": "739"},
   {"release date": "Mon Jan 01 2018", "contract type": "supplies and service contracts", "contract value": "5203", "supplier size": "667"},
   {"release date": "Wed Jan 03 2018", "contract type": "works contracts", "contract value": "2086", "supplier size": "140"},
   {"release date": "Sun Jan 07 2018", "contract type": "works contracts", "contract value": "2068", "supplier size": "144"},
   {"release date": "Mon Jan 08 2018", "contract type": "supplies and service contracts", "contract value": "7184", "supplier size": "737"},
   {"release date": "Wed Jan 10 2018", "contract type": "social and other specific services", "contract value": "9713", "supplier size": "289"},
   {"release date": "Fri Jan 19 2018", "contract type": "works contracts", "contract value": "27808", "supplier size": "883"},
   {"release date": "Sun Jan 28 2018", "contract type": "supplies and service contracts", "contract value": "2897", "supplier size": "114"},
   {"release date": "Mon Jan 29 2018", "contract type": "supplies and service contracts", "contract value": "5782", "supplier size": "265"},
   {"release date": "Tue Jan 30 2018", "contract type": "supplies and service contracts", "contract value": "39119", "supplier size": "1095"},
   {"release date": "Wed Jan 31 2018", "contract type": "works contracts", "contract value": "10601", "supplier size": "273"},
   {"release date": "Wed Jan 31 2018", "contract type": "social and other specific services", "contract value": "65970", "supplier size": "1464"},
   {"release date": "Fri Feb 02 2018", "contract type": "works contracts", "contract value": "2452", "supplier size": "124"},
   {"release date": "Fri Feb 02 2018", "contract type": "supplies and service contracts", "contract value": "12765", "supplier size": "669"},
   {"release date": "Mon Feb 05 2018", "contract type": "social and other specific services", "contract value": "62673", "supplier size": "719"},
   {"release date": "Wed Feb 14 2018", "contract type": "social and other specific services", "contract value": "65469", "supplier size": "1494"},
   {"release date": "Wed Feb 14 2018", "contract type": "works contracts", "contract value": "38518", "supplier size": "811"},
   {"release date": "Mon Feb 19 2018", "contract type": "social and other specific services", "contract value": "2910", "supplier size": "55"},
   {"release date": "Mon Feb 19 2018", "contract type": "supplies and service contracts", "contract value": "47211", "supplier size": "797"},
   {"release date": "Thu Feb 22 2018", "contract type": "supplies and service contracts", "contract value": "1493", "supplier size": "148"},
   {"release date": "Fri Feb 23 2018", "contract type": "social and other specific services", "contract value": "2467", "supplier size": "98"},
   {"release date": "Sat Feb 24 2018", "contract type": "supplies and service contracts", "contract value": "14047", "supplier size": "428"},
   {"release date": "Wed Feb 28 2018", "contract type": "supplies and service contracts", "contract value": "40773", "supplier size": "1192"},
   {"release date": "Thu Mar 01 2018", "contract type": "supplies and service contracts", "contract value": "2280", "supplier size": "53"},
   {"release date": "Thu Mar 08 2018", "contract type": "works contracts", "contract value": "26123", "supplier size": "533"},
   {"release date": "Fri Mar 16 2018", "contract type": "social and other specific services", "contract value": "2835", "supplier size": "99"},
   {"release date": "Fri Mar 16 2018", "contract type": "supplies and service contracts", "contract value": "1503", "supplier size": "103"},
   {"release date": "Sat Mar 24 2018", "contract type": "works contracts", "contract value": "14984", "supplier size": "328"},
   {"release date": "Sun Apr 01 2018", "contract type": "works contracts", "contract value": "27438", "supplier size": "1240"},
   {"release date": "Tue Apr 03 2018", "contract type": "supplies and service contracts", "contract value": "2651", "supplier size": "69"},
   {"release date": "Thu Apr 12 2018", "contract type": "works contracts", "contract value": "14303", "supplier size": "346"},
   {"release date": "Tue Apr 17 2018", "contract type": "supplies and service contracts", "contract value": "9065", "supplier size": "329"},
   {"release date": "Tue Apr 24 2018", "contract type": "supplies and service contracts", "contract value": "10677", "supplier size": "533"},
   {"release date": "Sat Apr 28 2018", "contract type": "social and other specific services", "contract value": "1834", "supplier size": "73"},
   {"release date": "Sat May 05 2018", "contract type": "supplies and service contracts", "contract value": "32687", "supplier size": "1082"},
   {"release date": "Sat May 05 2018", "contract type": "works contracts", "contract value": "14842", "supplier size": "361"},
   {"release date": "Thu May 10 2018", "contract type": "works contracts", "contract value": "74338", "supplier size": "1035"},
   {"release date": "Fri May 18 2018", "contract type": "supplies and service contracts", "contract value": "2672", "supplier size": "130"},
   {"release date": "Thu May 24 2018", "contract type": "supplies and service contracts", "contract value": "46274", "supplier size": "796"},
   {"release date": "Wed May 30 2018", "contract type": "works contracts", "contract value": "2128", "supplier size": "132"},
   {"release date": "Fri Jun 08 2018", "contract type": "social and other specific services", "contract value": "9448", "supplier size": "628"},
   {"release date": "Sun Jun 10 2018", "contract type": "works contracts", "contract value": "1897", "supplier size": "121"},
   {"release date": "Thu Jun 14 2018", "contract type": "social and other specific services", "contract value": "2872", "supplier size": "149"},
   {"release date": "Sat Jun 23 2018", "contract type": "works contracts", "contract value": "49658", "supplier size": "694"},
   {"release date": "Fri Jun 29 2018", "contract type": "supplies and service contracts", "contract value": "1634", "supplier size": "65"},
   {"release date": "Sun Jul 08 2018", "contract type": "supplies and service contracts", "contract value": "66447", "supplier size": "1118"},
   {"release date": "Mon Jul 16 2018", "contract type": "social and other specific services", "contract value": "38243", "supplier size": "819"},
   {"release date": "Tue Jul 17 2018", "contract type": "social and other specific services", "contract value": "44239", "supplier size": "1499"},
   {"release date": "Fri Jul 20 2018", "contract type": "works contracts", "contract value": "36625", "supplier size": "1130"},
   {"release date": "Fri Jul 20 2018", "contract type": "works contracts", "contract value": "42135", "supplier size": "1076"},
   {"release date": "Mon Jul 23 2018", "contract type": "social and other specific services", "contract value": "25602", "supplier size": "617"},
   {"release date": "Sat Jul 28 2018", "contract type": "social and other specific services", "contract value": "51597", "supplier size": "1435"},
   {"release date": "Mon Aug 06 2018", "contract type": "social and other specific services", "contract value": "1595", "supplier size": "101"},
   {"release date": "Thu Aug 09 2018", "contract type": "supplies and service contracts", "contract value": "1222", "supplier size": "123"},
   {"release date": "Sat Aug 18 2018", "contract type": "social and other specific services", "contract value": "2754", "supplier size": "129"},
   {"release date": "Thu Aug 23 2018", "contract type": "supplies and service contracts", "contract value": "52629", "supplier size": "1214"},
   {"release date": "Sat Aug 25 2018", "contract type": "social and other specific services", "contract value": "66354", "supplier size": "1450"},
   {"release date": "Sun Sep 02 2018", "contract type": "supplies and service contracts", "contract value": "12078", "supplier size": "432"},
   {"release date": "Sun Sep 09 2018", "contract type": "works contracts", "contract value": "67083", "supplier size": "1499"},
   {"release date": "Sat Sep 15 2018", "contract type": "social and other specific services", "contract value": "11863", "supplier size": "251"},
   {"release date": "Mon Sep 17 2018", "contract type": "works contracts", "contract value": "2923", "supplier size": "55"},
   {"release date": "Wed Sep 26 2018", "contract type": "supplies and service contracts", "contract value": "68231", "supplier size": "1478"},
   {"release date": "Mon Oct 01 2018", "contract type": "social and other specific services", "contract value": "1356", "supplier size": "62"},
   {"release date": "Tue Oct 09 2018", "contract type": "works contracts", "contract value": "12597", "supplier size": "480"},
   {"release date": "Wed Oct 10 2018", "contract type": "supplies and service contracts", "contract value": "2690", "supplier size": "76"},
   {"release date": "Tue Oct 16 2018", "contract type": "social and other specific services", "contract value": "25752", "supplier size": "1443"},
   {"release date": "Sat Oct 20 2018", "contract type": "supplies and service contracts", "contract value": "40758", "supplier size": "994"},
   {"release date": "Sun Oct 28 2018", "contract type": "works contracts", "contract value": "31085", "supplier size": "674"},
   {"release date": "Sun Oct 28 2018", "contract type": "supplies and service contracts", "contract value": "8287", "supplier size": "749"},
   {"release date": "Sat Nov 03 2018", "contract type": "works contracts", "contract value": "72748", "supplier size": "681"},
   {"release date": "Thu Nov 08 2018", "contract type": "social and other specific services", "contract value": "11970", "supplier size": "473"},
   {"release date": "Sun Nov 11 2018", "contract type": "supplies and service contracts", "contract value": "1805", "supplier size": "78"},
   {"release date": "Sun Nov 18 2018", "contract type": "supplies and service contracts", "contract value": "1356", "supplier size": "146"},
   {"release date": "Tue Nov 20 2018", "contract type": "works contracts", "contract value": "1988", "supplier size": "86"},
   {"release date": "Mon Nov 26 2018", "contract type": "supplies and service contracts", "contract value": "5454", "supplier size": "614"},
   {"release date": "Mon Dec 03 2018", "contract type": "social and other specific services", "contract value": "2225", "supplier size": "107"},
   {"release date": "Sat Dec 08 2018", "contract type": "works contracts", "contract value": "11189", "supplier size": "532"},
   {"release date": "Sat Dec 08 2018", "contract type": "social and other specific services", "contract value": "62644", "supplier size": "1314"},
   {"release date": "Tue Dec 11 2018", "contract type": "social and other specific services", "contract value": "40210", "supplier size": "1183"},
   {"release date": "Sat Dec 15 2018", "contract type": "social and other specific services", "contract value": "58130", "supplier size": "677"},
   {"release date": "Thu Dec 20 2018", "contract type": "supplies and service contracts", "contract value": "8286", "supplier size": "432"},
   {"release date": "Wed Dec 26 2018", "contract type": "social and other specific services", "contract value": "1877", "supplier size": "85"},
   {"release date": "Mon Dec 31 2018", "contract type": "works contracts", "contract value": "36917", "supplier size": "762"},
   {"release date": "Mon Dec 31 2018", "contract type": "social and other specific services", "contract value": "1284", "supplier size": "113"},
   {"release date": "Mon Dec 31 2018", "contract type": "social and other specific services", "contract value": "12328", "supplier size": "415"},
   {"release date": "Wed Jan 02 2019", "contract type": "works contracts", "contract value": "9170", "supplier size": "449"},
   {"release date": "Sun Jan 06 2019", "contract type": "social and other specific services", "contract value": "73355", "supplier size": "687"},
   {"release date": "Tue Jan 15 2019", "contract type": "social and other specific services", "contract value": "6861", "supplier size": "256"},
   {"release date": "Wed Jan 16 2019", "contract type": "supplies and service contracts", "contract value": "6593", "supplier size": "715"},
   {"release date": "Tue Jan 22 2019", "contract type": "works contracts", "contract value": "12808", "supplier size": "737"},
   {"release date": "Wed Jan 30 2019", "contract type": "works contracts", "contract value": "13160", "supplier size": "325"},
   {"release date": "Wed Jan 30 2019", "contract type": "supplies and service contracts", "contract value": "49174", "supplier size": "725"},
   {"release date": "Thu Feb 07 2019", "contract type": "works contracts", "contract value": "39243", "supplier size": "948"},
   {"release date": "Wed Feb 13 2019", "contract type": "social and other specific services", "contract value": "14055", "supplier size": "587"},
   {"release date": "Sat Feb 16 2019", "contract type": "works contracts", "contract value": "10618", "supplier size": "549"},
   {"release date": "Mon Feb 18 2019", "contract type": "supplies and service contracts", "contract value": "2833", "supplier size": "85"},
   {"release date": "Wed Feb 20 2019", "contract type": "social and other specific services", "contract value": "74491", "supplier size": "620"},
   {"release date": "Sat Feb 23 2019", "contract type": "social and other specific services", "contract value": "1035", "supplier size": "50"},
   {"release date": "Sat Mar 02 2019", "contract type": "works contracts", "contract value": "9095", "supplier size": "447"},
   {"release date": "Thu Mar 07 2019", "contract type": "works contracts", "contract value": "9498", "supplier size": "291"},
   {"release date": "Sat Mar 16 2019", "contract type": "works contracts", "contract value": "6129", "supplier size": "587"},
   {"release date": "Tue Mar 19 2019", "contract type": "works contracts", "contract value": "2162", "supplier size": "64"},
   {"release date": "Tue Mar 26 2019", "contract type": "social and other specific services", "contract value": "2759", "supplier size": "131"},
   {"release date": "Thu Mar 28 2019", "contract type": "social and other specific services", "contract value": "9120", "supplier size": "489"},
   {"release date": "Wed Apr 03 2019", "contract type": "social and other specific services", "contract value": "10094", "supplier size": "329"},
   {"release date": "Fri Apr 12 2019", "contract type": "supplies and service contracts", "contract value": "52594", "supplier size": "1264"},
   {"release date": "Mon Apr 15 2019", "contract type": "social and other specific services", "contract value": "14588", "supplier size": "272"},
   {"release date": "Mon Apr 15 2019", "contract type": "works contracts", "contract value": "8620", "supplier size": "698"},
   {"release date": "Sun Apr 21 2019", "contract type": "supplies and service contracts", "contract value": "2165", "supplier size": "64"},
   {"release date": "Sat Apr 27 2019", "contract type": "supplies and service contracts", "contract value": "2773", "supplier size": "50"},
   {"release date": "Sun May 05 2019", "contract type": "works contracts", "contract value": "12166", "supplier size": "619"},
   {"release date": "Wed May 08 2019", "contract type": "works contracts", "contract value": "74128", "supplier size": "1473"},
   {"release date": "Wed May 08 2019", "contract type": "works contracts", "contract value": "2848", "supplier size": "147"},
   {"release date": "Mon May 13 2019", "contract type": "supplies and service contracts", "contract value": "33847", "supplier size": "521"},
   {"release date": "Wed May 22 2019", "contract type": "works contracts", "contract value": "2528", "supplier size": "112"},
   {"release date": "Sat May 25 2019", "contract type": "works contracts", "contract value": "2580", "supplier size": "112"},
   {"release date": "Sat Jun 01 2019", "contract type": "works contracts", "contract value": "14682", "supplier size": "521"},
   {"release date": "Mon Jun 10 2019", "contract type": "supplies and service contracts", "contract value": "58146", "supplier size": "1242"},
   {"release date": "Mon Jun 10 2019", "contract type": "supplies and service contracts", "contract value": "27861", "supplier size": "1067"},
   {"release date": "Tue Jun 11 2019", "contract type": "social and other specific services", "contract value": "1390", "supplier size": "79"},
   {"release date": "Sun Jun 16 2019", "contract type": "social and other specific services", "contract value": "66291", "supplier size": "583"}
]